config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  root 'store#index', as: 'store_index'
  resources :products
  
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :line_items, dependent: :destroy

	def add_product(product)
		current_item = line_items.find_by(product_id: product.id)

		if current_item
			current_item.quantity += 1
		else
			current_item = line_items.build(product_id: product.id)
		end
		current_item
	end

	def total_price
		line_items.sum { |item| item.total_price }
	end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total_price
    product.price * quantity
  end

end

app/models/product.rb
class Product < ApplicationRecord
	has_many :line_items
	before_destroy :ensure_not_referenced_by_any_line_item

	validates :title, :description, :image_url, presence: true
	validates :title, uniqueness: true
	validates :title, length: { minimum: 5, message: 'must be equal to or greater than 5 characters.' }
	validates :price, numericality: { greater_than_or_equal_to: 0.01 }
	validates :image_url, allow_blank: true, format: {
			with: %r{\.(gif|jpg|png)\z}i, 
			message: 'must be a URL for GIF, JPG or PNG image.'
	}

	private

		def ensure_not_referenced_by_any_line_item
			unless line_items.empty?
				errors.add(:base, 'Line Items present!')
				throw :abort
			end
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[ show edit update destroy ]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart


  def index
    @carts = Cart.all
  end

  def show
  end
 
  def new
    @cart = Cart.new
  end

  def edit
  end

  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to store_index_url,
      notice: 'Your cart is currently empty' }
      format.json { head :no_content }
    end
  end

  private
    def set_cart
      @cart = Cart.find(params[:id])
    end

    def cart_params
      params.fetch(:cart, {})
    end

    def invalid_cart
      logger.error "Atempt to access invalid cart -> #{params[:id]}"
      redirect_to store_index_url, notice:  "Invalid cart!"
    end
end

app/controllers/concerns/current_cart.rb
module CurrentCart

	private

		def set_cart
			@cart = Cart.find(session[:cart_id])
		rescue ActiveRecord::RecordNotFound
			@cart = Cart.create
			session[:cart_id] = @cart.id
		end

end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
	include CurrentCart
	before_action :set_cart, only: %i[ create ]
  before_action :set_line_item, only: %i[ show edit update destroy ]

  def index
    @line_items = LineItem.all
  end

  def show
  end

  def new
    @line_item = LineItem.new
  end

  def edit
  end

  def create
		product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product)

    respond_to do |format|
      if @line_item.save
        format.turbo_stream { @current_item = @line_item }
        format.html { redirect_to store_index_url }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to line_item_url(@line_item), notice: "Line item was successfully updated." }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @line_item.destroy!

    respond_to do |format|
      format.html { redirect_to line_items_url, notice: "Line item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    def line_item_params
      params.require(:line_item).permit(:product_id, :cart_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
				# puts @product.errors.full_messages
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }

        @product.broadcast_replace_later_to 'products',
        partial: 'store/product'
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy!

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price)
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  include CurrentCart
  before_action :set_cart
  
  def index
		@products = Product.order(title: :asc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/carts/_cart.html.erb
<div id="<%= dom_id cart %>" >
	<h2 class="font-bold text-lg mb-3">Your Cart</h2>

	<table class="table-auto">
		<%= render cart.line_items %>
		<tfoot>
			<tr>
				<th class="text-right pr-2 pt-2" colspan="3">Total:</th>
				<td class="text-right pt-2 font-bold border-t-2 border-black">
					<%= number_to_currency(cart.total_price) %>
				</td>
			</tr>
		</tfoot>
	</table>

	<div class="flex flex-row gap-5 mt-5">
		<%= button_to "Empty cart", cart, method: :delete, 
			class: "px-3 py-2 text-sm font-medium text-center text-white bg-rose-600 
				rounded-lg hover:bg-rose-800 focus:ring-4 focus:outline-none focus:ring-rose-300 
				dark:bg-rose-600 dark:hover:bg-rose-700 dark:focus:ring-rose-800" %>		
	</div>

</div>

app/views/carts/_form.html.erb
<%= form_with(model: cart, class: "contents") do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing cart</h1>

  <%= render "form", cart: @cart %>

  <%= link_to "Show this cart", @cart, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to carts", carts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/carts/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Carts</h1>
    <%= link_to "New cart", new_cart_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="carts" class="min-w-full">
    <%= render @carts %>
  </div>
</div>

app/views/carts/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New cart</h1>

  <%= render "form", cart: @cart %>

  <%= link_to "Back to carts", carts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/carts/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @cart %>  
  </div>
</div>

app/views/layouts/_cart.html.erb
<% if @cart and not @cart.line_items.empty? %>
  <div id="cart" class="bg-white rounded p-2">
  <%= render @cart %>
  </div>
<% else %>
  <div id="cart"> </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pragprog Books Online Store</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
		<header class="bg-green-700">
      <%= image_tag 'logo.svg', alt: 'The Pragmatic Bookshelf' %>
      <h1><%= @page_title %></h1>
    </header>

    <section class="flex">
    <nav class="bg-green-900 p-6">
      
      <%= render partial: 'layouts/cart', locals: { cart: @cart } %>
      
        <ul class="text-gray-300 leading-8">
          <li><a href="/">Home</a></li>
          <li><a href="#">Questions</a></li>
          <li><a href="#">News</a></li>
          <li><a href="#">Contact</a></li>
        </ul>
      </nav>

      <main class="container mx-auto mt-4 px-5 flex">
        <%= yield %>
      </main>
    </section>
  </body>
</html>

app/views/line_items/_form.html.erb
<%= form_with(model: line_item, class: "contents") do |form| %>
  <% if line_item.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
        <% line_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :product_id %>
    <%= form.text_field :product_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :cart_id %>
    <%= form.text_field :cart_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<% if line_item == @current_item %>
  <tr class="line-item-highlight">
<% else %>  
  <tr>
<% end %>
  <td class="text-right"><%= line_item.quantity %></td>
  <td>&times;</td>
  <td class="pr-2">
    <%= line_item.product.title %>
  </td>
  <td class="text-right font-bold">
    <%= number_to_currency(line_item.total_price) %>
  </td>
</tr>

app/views/line_items/create.turbo_stream.erb
<%= turbo_stream.replace 'notece' do  %>
  <%= render partial: 'store/notice', locals: { notice: @notice } %>
<% end %>

<%= turbo_stream.replace 'cart' do  %>
  <%= render partial: 'layouts/cart', locals: { cart: @cart } %>
<% end %>

app/views/line_items/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing line item</h1>

  <%= render "form", line_item: @line_item %>

  <%= link_to "Show this line item", @line_item, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to line items", line_items_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/line_items/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Line items</h1>
    <%= link_to "New line item", new_line_item_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="line_items" class="min-w-full">
    <%= render @line_items %>
  </div>
</div>

app/views/line_items/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New line item</h1>

  <%= render "form", line_item: @line_item %>

  <%= link_to "Back to line items", line_items_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/line_items/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @line_item %>

    <%= link_to "Edit this line_item", edit_line_item_path(@line_item), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this line_item", line_item_path(@line_item), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to line_items", line_items_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product, class: "contents") do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 10, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :price %>
    <%= form.text_field :price, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p class="my-5">
    <strong class="block font-lg mb-1">Title:</strong>
    <%= product.title %>
  </p>
	<%= image_tag(product.image_url,
							class: 'object-contain w-40 h-48 rounded-lg shadow-md mr-6') %>
	<div>

  <p class="my-5">
    <strong class="block font-lg mb-1">Image url:</strong>
    <%= product.image_url %>
  </p>
	
  <p class="my-5">
    <strong class="block font-lg mb-1">Description:</strong>
    <%= product.description %>
  </p>


  <p class="my-5">
    <strong class="block font-lg mb-1">Price:</strong>
    <%= product.price %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this product", product, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this product", edit_product_path(product), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/products/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing product</h1>

  <%= render "form", product: @product %>

  <%= link_to "Show this product", @product, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to products", products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/products/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center pb-8">
    <h1 class="mx-auto font-bold text-4xl">Products</h1>
  </div>
  
  <table id="products" class="mx-auto">
    <tfoot>
      <tr>
        <td colspan="3">
          <div class="mt-8">
          <%= link_to "New product",
                      new_product_path,
                      class: "inline rounded-lg py-3 px-5 bg-green-600
                text-white block font-medium" %>
          </div>
        </td>
      </tr>
    </tfoot>
    <tbody>
      <% @products.each do |product| %>
      <tr class="<%= cycle("bg-green-50", "bg-white") %>">
        <td class="px-2 py-3">
          <%= image_tag(product.image_url, class: "w-40 drop-shadow-md rounded-md") %>
        </td>
        <td>
          <h1 class="text-xl font-bold mb-3"><%= product.title %></h1>
          <p>
            <%= truncate(strip_tags(product.description), length: 80) %>
          </p>
        </td>
        <td class="px-3">
          <ul>
            <li>
              <%= link_to "Show",
                          product,
                          class: "hover:underline" %>
            </li>
            <li>
              <%= link_to "Edit",
                          edit_product_path(product),
                          class: "hover:underline" %>
            </li>
            <li>
              <%= link_to "Destroy",
                          product,
                          class: "hover:underline",
                          data: { turbo_method: :delete,
                                  turbo_confirm: "Are you sure?" } %>
            </li>
          </ul>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/products/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New product</h1>

  <%= render "form", product: @product %>

  <%= link_to "Back to products", products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/products/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @product %>

    <%= link_to "Edit this product", edit_product_path(@product), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this product", product_path(@product), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to products", products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/store/_notice.html.erb
<% if notice.present? %>
		<p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg
							inline-block" id="notice">
			<%= notice %>
		</p>
  <% else %>
    <div id="notice"></div>
	<% end %>

app/views/store/_product.html.erb
<%= turbo_frame_tag(dom_id(product)) do %>
  <li class='flex mb-6'>
    <%= image_tag(product.image_url,
      class: 'object-contain w-40 h-48 rounded-lg shadow-md mr-6') %>

    <div>
      <h2 class="font-bold text-lg mb-3"><%= link_to product.title, product, data: { turbo: false } %></h2>

      <p>
        <%= truncate(strip_tags(product.description), length: 80) %>
      </p>

      <div class="mt-3">
        <%= number_to_currency(product.price) %>

        <%= button_to 'Add to cart', line_items_path(product_id: product),
            class: 'inline-block px-3 py-2 text-sm font-medium text-center text-white bg-green-600 
            rounded-lg hover:bg-green-800 focus:ring-4 focus:outline-none focus:ring-green-300 
            dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800' %>
      </div>
    </div>
  </li>
<% end %>

app/views/store/index.html.erb
<div class="w-full">
	<%= render 'notice' %>

	<h1 class="font-bold text-xl mb-6 pb-2 border-b-2">
		Your Pragmatic Catalog
	</h1>

	<%= turbo_stream_from 'products' %>

	<ul>
		<% cache @products do %>
			<% @products.each do |product| %>
				<% cache product do %>
					<%= render partial: 'product', object: product %>
				<% end %>
			<% end %>
		<% end %>
	</ul>
</div>